server:
  port: 9090

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: ${spring.application.name}
    description: Admin and Monitor The Services
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom
    spring-cloud-version: '@spring-cloud.version@'
    spring-admin-version: '@spring-boot-admin.version@'