server:
  port: 8888

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URL}
          default-label: master
          clone-on-start: true
          search-paths: # Search in this GitHub path
            - 'Properties'
          basedir: configs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: Configuration Server
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom
    spring-cloud-version: '@spring-cloud.version@'
    spring-admin-version: '@spring-boot-admin.version@'