server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SarathVedha/Employee-Management-MicroService-Configs.git
          default-label: master
          clone-on-start: true
          search-paths: # Search in this GitHub path
            - 'Properties'
          basedir: configs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: Configuration Server
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom
    spring-cloud-version: '@spring-cloud.version@'