server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: ${spring.application.name}
    description: SERVICE-REGISTRY
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom
    spring-cloud-version: '@spring-cloud.version@'