spring:
  application:
    name: ORGANIZATION-SERVICE
  profiles:
    active: ${ORGANIZATION_APP_PROFILE}
  config: # Get properties From Config Server, optional:configserver:http://localhost:8888 -> For Local add URL as Env Variable in STS or Intellij
    import: optional:configserver:${CONFIG_SERVICE_URL}