server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost/organization_db
    username: postgres
    password: Rockers12$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    config:
      enabled: false
#  config:
#    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  health:
    circuitbreakers:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
  level:
    org.springframework.web: DEBUG

info:
  app:
    name: ORGANIZATION-SERVICE
    description: Organization Service Provides CURD REST APIs
    environment: ${spring.profiles.active}
    version: v1.0