server:
  port: 8081

spring:
  datasource:
    url: ${EMPLOYEE_SERVICE_DB_URL}
    username: ${EMPLOYEE_SERVICE_DB_USERNAME}
    password: ${EMPLOYEE_SERVICE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  boot: # Spring Admin Server URL
    admin:
      client:
        url: ${ADMIN_SERVICE_URL}
  rabbitmq: # Rabbit MQ Configs
    host: ${RABBIT_MQ_URL}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}/eureka/

# http://localhost:8080/employee-service/actuator/refresh
# http://localhost:8080/actuator/busrefresh
test:
  config:
    server: Message From Properties Updated MQ Bus

#Circuit Breaker Because Employee Service Depends On Department Service
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
        sliding-window-size: 5
  retry: # Circuit Breaker Retry if service down tries 3 times with gap 1s, if 3 times fails redirect to fallback method
    instances:
      EMPLOYEE-SERVICE:
        max-attempts: 3
        wait-duration: 1s

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  tracing: # Zipkin
    sampling: # Default value is 0.1 mean only 10% of the REST Calls will be traced. 1.0 Will trace each REST Call and get a display.
      probability: 1.0
  zipkin:
    tracing: # ZipKin Will be Autoconfigured in this url(http://localhost:9411/api/v2/spans), custom means you can add.
      endpoint: ${ZIPKIN_SERVER_URL}/api/v2/spans
  health: # For Circuit Breaker
    circuitbreakers:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
  level: # Enable DEBUG For REST WEB Logs
    org.springframework.web: DEBUG

info:
  app:
    name: ${spring.application.name}
    description: Employee Service REST CURD APIs
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom
    spring-cloud-version: '@spring-cloud.version@'
    spring-admin-version: '@spring-boot-admin.version@'