spring:
  application:
    name: EMPLOYEE-SERVICE
  cloud:
    config:
      enabled: true
  config: # Get properties From Config Server
    import: optional:configserver:http://localhost:8888
  rabbitmq: # Rabbit MQ Configs
    host: localhost
    port: 5672
    username: guest
    password: guest

management: # Zipkin
  tracing:
    sampling: # Default value is 0.1 mean only 10% of the REST Calls will be traced. 1.0 Will trace each REST Call and get a display.
      probability: 1.0
  zipkin:
    tracing: # ZipKin Will be Autoconfigured in this url(http://localhost:9411/api/v2/spans), custom means you can add.
      endpoint: http://localhost:9411/api/v2/spans
  health: # For Circuit Breaker
    circuitbreakers:
      enabled: true

#Circuit Breaker Because Employee Service Depends On Department Service
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
        sliding-window-size: 5
  retry: # Circuit Breaker Retry if service down tries 3 times with gap 1s, if 3 times fails redirect to fallback method
    instances:
      EMPLOYEE-SERVICE:
        max-attempts: 3
        wait-duration: 1s

logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
  level: # Enable DEBUG For REST WEB Logs
    org.springframework.web: DEBUG